name: 'demo_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'elementary'

vars:
  'dbt_date:time_zone': 'Asia/Kolkata'
source-paths : ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
#data-paths : ["data"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  demo_dbt:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
      +tags:
          - t1
       
    marts:
      +materialized: table
      +schema: pharma_fact_dim
      +tags:
          - t2

    elementary:
      +schema: "elementary"
   