version: 2

models:
  - name: dim_channel
    description: "This Dimension table contains details of store Class of buyer (Hospital, Pharmacy) and their respective ID's"
    columns:
     
      - name: channel_id
        description: "This is  unique identifier for  channel"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key

      - name: channel
        description: "Class of buyer (Hospital, Pharmacy)"

  - name: dim_city
    description: "This Dimension table contains details of  the distinct cities of customers and their ID's,longitude and latitude"
    columns:
      
      - name: city_id
        description: "This is  unique identifier for  cities"
        tests:
          - unique
          - not_null
          

      - name: city
        description: "name of Customer's city"

      - name: longitude
        description: "Customer's Geo Latitude"

      - name: latitude
        description: "Customer's Geo Longitude"

      - name: country_id
        description: "This is  unique identifier for  different countries"

  - name: dim_country
    description: "This Dimension table contains details of countries of customers and ID's for countries"
    columns:
      
      - name: country_id
        description: "This is  unique identifier for  different countries"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: country
        description: "name of customers country"

  - name: dim_customer
    description: "This Dimension table contains the details of all distinct customers names their respective id's,cities anf city id's"
    columns:
      
      - name: customer_id
        description: "This is  unique identifier for  different customers"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: customer_name
        description: "names of customers"

      - name: city
        description: "cities of customers"

      - name: city_id
        description: "This is  unique identifier for  different cities"

  - name: dim_month
    description: " This Dimension Table contains details about the Month sale was made and months respective id's"
    columns:
     
      - name: month_id
        description: "This is  unique identifier for  different months"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: month
        description: "Month when sale was made"

  - name: dim_distributor
    description: "This Dimension table contains details about the different Wholesaler and their id's"
    columns:
      
      - name: distributor_id
        description: "This is  unique identifier for  different distributors"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key

      - name: distributor
        description: "Name of Wholesaler"

  - name: dim_product
    description: "This Dimension Table contains details about the Name of Drug and Class of Drug (Antibiotics, etc.) and their id's"
    columns:
      

      - name: product_id
        description: "This is  unique identifier for  different products"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: product_name
        description: "Name of Drugs"

      - name: product_class
        description: "Class of Drug (Antibiotics, etc.)"

  - name: dim_sales_rep
    description: "This Dimension Table contains details about the Name of the Sales resentatives who facilitated the sale,sales Team and their id's"
    columns:
      
      - name: sales_rep_id
        description: "This is  unique identifier for  different sales rep's"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: sales_rep
        description: "Name of the Sales resentatives who facilitated the sale"

      - name: sales_team_id
        description: "This is  unique identifier for  different sales Team"

  - name: dim_sales_team
    description: "This Dimension Table contains details about the Sale resentatives's team and Sales resentatives's Manager Names and their id's"
    columns:
      
      - name: manager
        description: "Sales resentatives's Manager Name"

      - name: sales_team
        description: "Sale resentatives's team"

      - name: sales_team_id
        description: "This is  unique identifier for  different sales Team's"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


  - name: dim_subchannel
    description: "This Dimension Table contains details about the Sector of the buyer (Government, Private, etc.) and ids for subchannels"
    columns:
      
      - name: subchannel_id
        description: "This is  unique identifier for  subchannels"
        tests:
          - unique
          - not_null
          - dbt_constraints.primary_key


      - name: sub_channel
        description: "Sector of the buyer (Government, Private, etc.)"

      - name: channel_id
        description: "This is  unique identifier for  channels"

  - name: fact_sales
    description: contains sales transaction across dims included in this data model.
    columns:
      

      - name: subchannel_id
        description: "This is  unique identifier for  subchannels"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_subchannel')
              pk_column_name: subchannel_id

       
      - name: distributor_id
        description: "This is  unique identifier for  distributors"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_distributor')
              pk_column_name: distributor_id


      - name: month_id
        description: "This is  unique identifier for  months"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_month')
              pk_column_name: month_id

      - name: sales_rep_id
        description: "This is  unique identifier for  sales rep"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_sales_rep')
              pk_column_name: sales_rep_id


      - name: product_id
        description: "This is  unique identifier for  products"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_product')
              pk_column_name: product_id
          

      - name: customer_id
        description: "This is  unique identifier for  customers"
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('dim_customer')
              pk_column_name: customer_id


      - name: city_id
        description: "This is  unique identifier for  cities"

      - name: price
        description: "Price for product was sold for"

      - name: quantity
        description: "Quantity purchased"

      - name: sales
        description: "Amount made from sale"

      - name: year
        description: "Year sale was made"


